// Cursos da Feira de Profissões: alimenta o formulário de cadastro (curso de interesse)
// e as páginas da seção CURSOS (/cursos e /cursos/:slug).
//
// - valor:     texto exato gravado em usuarios.curso_interesse (não alterar sem migrar os dados)
// - imagem:    nome do arquivo em public/img/cursos SEM extensão (aceita .jpg, .jpeg, .png ou .webp).
//              Cursos que existem em mais de um turno podem compartilhar a mesma imagem.
//              Se o arquivo ainda não existir, a página mostra um espaço reservado.
// - descricao: texto da página; deixe '' enquanto não estiver escrito ("Descrição em breve").
//              Parágrafos separados por linha em branco.
const fs = require('fs');
const path = require('path');

const PASTA_IMAGENS = path.join(__dirname, '..', 'public', 'img', 'cursos');
const EXTENSOES = ['.jpg', '.jpeg', '.png', '.webp'];

const CURSOS = [
  { slug: 'desenvolvimento-de-sistemas-manha', nome: 'Desenvolvimento de Sistemas', modalidade: 'Técnico integrado ao Ensino Médio (M-Tec)', periodo: 'Manhã', imagem: 'Técnico em Desenvolvimento de Sistemas', valor: 'Desenvolvimento de Sistemas-M-Tec-Manhã', descricao: 'É o profissional que analisa e projeta sistemas. Constrói, documenta, realiza testes e mantém sistemas de informação. Utiliza ambientes de desenvolvimento e linguagens de programação específica. Modela, implementa e mantém bancos de dados.O candidato que ingressar no curso técnico de Desenvolvimento de Sistemas, na modalidade AMS, poderá prosseguir os estudos em uma Fatec no curso superior de tecnologia em Análise e Desenvolvimento de Sistemas. Eixo Tecnológico: Informação e Comunicação - Mercado de trabalho: Empresas e departamentos de desenvolvimento de sistemas em organizações governamentais e não governamentais, podendo também atuar como profissional autônomo.' },
  { slug: 'eletronica-manha', nome: 'Eletrônica', modalidade: 'Técnico integrado ao Ensino Médio (M-Tec)', periodo: 'Manhã', imagem: 'Técnico em Eletrônica', valor: 'Eletrônica-M-Tec-Manhã', descricao: 'Participa do desenvolvimento de projetos. Executa a instalação e a manutenção de equipamentos e sistemas eletrônicos e de automação. Faz medições e testes com equipamentos eletrônicos. Realiza procedimentos de controle de qualidade e gestão da produção de equipamentos eletrônicos. - Eixo Tecnológico: Controle e Processos Industriais - Mercado de trabalho: Indústrias; laboratórios de controle de qualidade e de manutenção; empresas de informática, de telecomunicações e de produtos eletrônicos.' },
  { slug: 'marketing-manha', nome: 'Marketing', modalidade: 'Técnico integrado ao Ensino Médio (M-Tec)', periodo: 'Manhã', imagem: 'Técnico em Marketing', valor: 'Marketing-M-Tec-Manhã', descricao: 'O estudante vai aprender que marketing é mais do que publicidade. É um processo que começa por entender as necessidades do consumidor para desenvolver produtos, serviços e ideias que serão comercializados. Para estudar esse assunto, o aluno vai precisar de conhecimentos de língua portuguesa, geografia e matemática. O estudante vai aprender a definir o público-alvo de cada produto ou serviço, assim como aprenderá a analisar esse processo de aproximação e troca entre vendedores e compradores. O aluno estudará, ainda, as formas de utilizar as ferramentas de comunicação, como publicidade, telemarketing, promoção de vendas etc. No curso, o estudante vai aprender também a criar logotipos, rótulos e embalagens. Administração de empresas, Legislação (como o Código de Defesa do Consumidor) e Inglês e Espanhol para leitura de textos completam a formação técnica em Marketing. - Eixo Tecnológico: Gestão e Negócios - Mercado de trabalho: No departamento de Marketing em empresas de qualquer setor, comércios, ONGs e agências de comunicação ou publicidade. - Atuação: Pode elaborar pesquisas de mercado para identificar o comportamento do consumidor. No ponto de venda (como supermercados, shoppings, lojas etc.), pode realizar a demonstração de produtos e montar peças e materiais de promoção, além de negociar espaços para melhor expor os produtos que serão vendidos. Pode trabalhar elaborando orçamento para a execução de ações (como promoções, propagandas etc.), calculando quanto se vai gastar para realizar cada uma. O técnico em Marketing pode ainda acompanhar as ações para verificar se os resultados foram positivos ou negativos. Em pequenas empresas, pode criar logotipos, rótulos e gerar conteúdo para as redes sociais.' },
  { slug: 'recursos-humanos-manha', nome: 'Recursos Humanos', modalidade: 'Técnico integrado ao Ensino Médio (M-Tec)', periodo: 'Manhã', imagem: 'Técnico em Recursos Humanos', valor: 'Recursos Humanos-M-Tec-Manhã', descricao: 'O estudante vai precisar de conhecimentos de língua portuguesa, matemática e história para compreender o curso e aprender a realizar as tarefas sob a responsabilidade do setor de Recursos Humanos de uma empresa, como contratação, demissão e aposentadoria de funcionários e oferta de benefícios (vale-transporte, plano de saúde, vale-refeição etc.), entre outras atividades. Por isso, será importante também estudar as leis que regulam os direitos e deveres do empregador e dos empregados (legislação trabalhista). O estudante vai aprender ainda noções de psicologia para entender como as pessoas se relacionam no ambiente de trabalho, realizar processos de recrutamento e seleção de novos funcionários e promover ações de motivação. - Eixo Tecnológico: Gestão e Negócios - Mercado de trabalho: No setor de Recursos Humanos ou na área administrativa de empresas públicas e privadas de qualquer segmento, empresas de treinamento e desenvolvimento e agências de emprego. - Atuação: Anuncia vagas de emprego, descrevendo as atribuições do cargo a ser preenchido; aplica testes em processos seletivos; realiza cálculos para determinar os valores que serão descontados no salário dos funcionários, como o Imposto de Renda e a contribuição ao INSS, além de porcentagem referente a benefícios, como vale-transporte, plano de saúde etc.; insere informações no sistema para a geração de demonstrativos de pagamentos (holerites ou contracheques); cuida da documentação necessária para aposentadoria, contratação e demissão de profissionais, inclusive preenchendo informações na carteira de trabalho; organiza e arquiva documentos do setor; registra e controla período de férias e afastamento de funcionários; e auxilia no treinamento e capacitação dos empregados.' },
  { slug: 'programacao-de-jogos-digitais-tarde', nome: 'Programação de Jogos Digitais', modalidade: 'Técnico integrado ao Ensino Médio (M-Tec)', periodo: 'Tarde', imagem: 'Técnico em Programação de Jogos Digitais', valor: 'Programação de Jogos Digitais-M-Tec-Tarde', descricao: 'O estudante vai aprender a criar jogos para console, computador, web, celulares, tablets e smartphone do começo ao fim: desde a pesquisa do público-alvo, passando pela quantidade de jogadores e desenvolvimento de personagens, até a identidade visual. Para isso, o aluno vai estudar linguagem de programação para games, computação gráfica, animação e roteiro. Ao longo do curso, o estudante vai rever assuntos de matemática, como geometria, para criar ambientes e personagens em 3D por meio de softwares específicos e retomar princípios da física, como movimento e inércia, para fazer animações. O aluno vai aprender também a elaborar roteiros para jogos, isto é, a escrever a história, criar os personagens, descrever cenários e customizar trilhas sonoras. O curso abordará ainda a legislação sobre direitos autorais e marketing para jogos digitais. - Eixo Tecnológico: Informação e Comunicação - Mercado de trabalho: Empresas de desenvolvimento de jogos. - Atuação: O técnico vai desenvolver jogos digitais, geralmente, em uma equipe onde cada integrante é responsável por uma das etapas da criação ou programação, como concepção, animação, elaboração de cenário e de personagens, pesquisa de público-alvo etc. O profissional também realiza testes e redige tutoriais sobre as fases do game e explicações sobre como jogar.' },
  { slug: 'farmacia-tarde', nome: 'Farmácia', modalidade: 'Técnico integrado ao Ensino Médio (M-Tec)', periodo: 'Tarde', imagem: 'Técnico em Farmácia', valor: 'Farmácia-M-Tec-Tarde', descricao: 'O curso tem base na química, para maior compreensão sobre os elementos utilizados em farmácias de manipulação; na biologia, para entender as reações que as medicações causam no corpo humano; na matemática, para fazer cálculos de miligramas na orientação aos pacientes e no inglês instrumental. O aluno também aprende sobre logística, ética e gestão farmacêutica. - Eixo Tecnológico: Ambiente e Saúde - Mercado de trabalho: Drogarias, indústrias farmacêuticas, postos de medicação, hospitais, farmácia de manipulação, distribuidoras de medicamentos. - Atuação: Manipula medicamentos, realiza testes de controle de qualidade, auxilia nas rotinas das farmácias, no armazenamento dos medicamentos e no controle do estoque. Orienta os pacientes sobre receitas medicas, conservação e uso correto de cada medicamento.' },
  { slug: 'biotecnologia-tarde', nome: 'Biotecnologia', modalidade: 'Técnico', periodo: 'Tarde', imagem: 'Técnico em Biotecnologia', valor: 'Biotecnologia-Tarde', descricao: 'No curso de biotecnologia, o conhecimento biológico interage com a química e a física. O aluno aprenderá temas como ecologia, genética e bioética, entre outros. A química e a matemática também são essenciais para entender estatísticas, manipulação de substâncias, interpretação de problemas e desenvolvimento de cálculos simples. Eixo Tecnológico:Ambiente e Saúde Mercado de trabalho: Indústrias alimentícia, farmacêutica, agroindústria, polícia científica, empresas do setor de bioquímica e biocombustíveis. Atuação: Executará atividades associadas às áreas de saúde (vacinas e produtos para estudos clínicos), alimentação (produtos e desenvolvimento vegetal e animal), indústria química e desenvolvimento ambiental. Pode trabalhar ainda com atividades relacionadas a perícia criminal, por meio da investigação genética e outros exames biológicos e bioquímicos, por exemplo.' },
  { slug: 'administracao-tarde', nome: 'Administração', modalidade: 'Técnico integrado ao Ensino Médio (M-Tec)', periodo: 'Tarde', imagem: 'Técnico em Administração', valor: 'Administração-M-Tec-Tarde', descricao: 'Como funcionam as organizações, desde empresas privadas até ONGs, passando por órgãos públicos, comércio e indústria. O estudante vai precisar de conhecimentos de língua portuguesa, matemática, história e geografia para compreender os principais assuntos do curso, como história da administração, evolução das organizações ao longo do tempo, contabilidade, leis que regulam o funcionamento das empresas e redação de documentos.O aluno vai aprender ainda a analisar as chances de um negócio ou produto ser bem-sucedido e o comportamento do consumidor. Estudará também técnicas de atendimento ao cliente, empreendedorismo (iniciativas para realizar novos negócios) e como uma organização planeja alcançar seus objetivos e define suas metas para o futuro.O candidato que ingressar no curso técnico de Administração, na modalidade AMS, poderá prosseguir os estudos em uma Fatec no curso superior de tecnologia em Processos Gerenciais.' },
  { slug: 'informatica-para-internet-noite', nome: 'Informática para Internet', modalidade: 'Técnico integrado ao Ensino Médio (M-Tec)', periodo: 'Noite', imagem: 'Técnico em Infonet', valor: 'Informática para Internet-M-Tec-Noite', descricao: 'O processo de criação de sites e o de desenvolvimento de programas que podem ser utilizados em páginas na internet. Para programar, o aluno vai estudar raciocínio lógico e linguagens de programação, que utiliza comandos para desenvolver funcionalidades e dar forma a um site. Além disso, o estudante aprenderá um pouco de design com o objetivo de tornar a página mais agradável e fácil de ser utilizada. O aluno aprenderá ainda como criar e alterar bancos de dados que vão alimentar os sites. Noções de marketing digital para a web e de empreendedorismo também serão ensinadas ao longo do curso. - Eixo Tecnológico: Informação e Comunicação - Mercado de trabalho: Empresas de desenvolvimento de sites ou de sistemas e empresas de marketing digital. O técnico também pode trabalhar por conta própria, como freelancer, prestando serviço a outras empresas. Atuação: Cria websites de acordo com as necessidades do cliente, identificando e sugerindo as melhores soluções; faz a manutenção de portais, sites e intranets; cuida da identidade visual das páginas de uma empresa; faz a customização de plataformas de conteúdo para web, como blogs e sites de comércio eletrônico; cria e realiza manutenção de bancos de dados para websites; adapta as páginas para abrigar vídeos, áudios e funções que facilitem a acessibilidade, como comandos de voz, por exemplo; trata e otimiza imagens para uso na internet; e prepara o layout de mensagens que são enviadas por e-mail (newsletter ou e-mail marketing), entre outras atividades.' },
  { slug: 'farmacia-noite', nome: 'Farmácia', modalidade: 'Técnico', periodo: 'Noite', imagem: 'Técnico em Farmácia', valor: 'Farmácia-Noite', descricao: 'O curso tem base na química, para maior compreensão sobre os elementos utilizados em farmácias de manipulação; na biologia, para entender as reações que as medicações causam no corpo humano; na matemática, para fazer cálculos de miligramas na orientação aos pacientes e no inglês instrumental. O aluno também aprende sobre logística, ética e gestão farmacêutica. - Eixo Tecnológico: Ambiente e Saúde - Mercado de trabalho: Drogarias, indústrias farmacêuticas, postos de medicação, hospitais, farmácia de manipulação, distribuidoras de medicamentos. - Atuação: Manipula medicamentos, realiza testes de controle de qualidade, auxilia nas rotinas das farmácias, no armazenamento dos medicamentos e no controle do estoque. Orienta os pacientes sobre receitas medicas, conservação e uso correto de cada medicamento.' },
  { slug: 'administracao-noite', nome: 'Administração', modalidade: 'Técnico integrado ao Ensino Médio (M-Tec)', periodo: 'Noite', imagem: 'Técnico em Administração', valor: 'Administração-M-Tec-Noite', descricao: 'Como funcionam as organizações, desde empresas privadas até ONGs, passando por órgãos públicos, comércio e indústria. O estudante vai precisar de conhecimentos de língua portuguesa, matemática, história e geografia para compreender os principais assuntos do curso, como história da administração, evolução das organizações ao longo do tempo, contabilidade, leis que regulam o funcionamento das empresas e redação de documentos.O aluno vai aprender ainda a analisar as chances de um negócio ou produto ser bem-sucedido e o comportamento do consumidor. Estudará também técnicas de atendimento ao cliente, empreendedorismo (iniciativas para realizar novos negócios) e como uma organização planeja alcançar seus objetivos e define suas metas para o futuro.O candidato que ingressar no curso técnico de Administração, na modalidade AMS, poderá prosseguir os estudos em uma Fatec no curso superior de tecnologia em Processos Gerenciais.' },
  { slug: 'eletroeletronica-noite', nome: 'Eletroeletrônica', modalidade: 'Técnico integrado ao Ensino Médio (M-Tec)', periodo: 'Noite', imagem: 'Técnico em Eletroeletrônica', valor: 'Eletroeletrônica-M-Tec-Noite', descricao: 'Planeja serviços de manutenção e instalação e realiza manutenções preventivas, preditivas e corretivas. Instala sistemas e componentes. Realiza medições e testes, como também desenvolve e executa projetos de instalações elétricas, circuitos eletrônicos e automação. Elabora documentação técnica. Planeja, instala e faz a manutenção de equipamentos e instalações eletroeletrônicas industriais. Projeta e instala sistemas de acionamento e controle. Propõe o uso eficiente da energia elétrica. Elabora, desenvolve e executa projetos de instalações elétricas em edificações em baixa tensão. - Eixo Tecnológico: Controle e Processos Industriais - Mercado de trabalho: Indústria eletroeletrônica, de manufatura e de processos, empresas de manutenção e automação, laboratórios de controle e de qualidade, de manutenção e pesquisa, empresas de consultoria na área, desenvolvimento de projetos e prestação de serviços.' },
  { slug: 'eletrotecnica-noite', nome: 'Eletrotécnica', modalidade: 'Técnico', periodo: 'Noite', imagem: 'Técnico em Eletrotécnica', valor: 'Eletrotécnica-Noite', descricao: 'O técnico instala, opera e mantém elementos de geração, transmissão e distribuição de energia; participa da elaboração e do desenvolvimento de instalações elétricas e de infraestrutura para sistemas de telecomunicações em edificações; planeja e executa a instalação e a manutenção de equipamentos e instalações; aplica medidas para o uso eficiente da energia e de fontes energéticas alternativas. Participa do projeto e instala sistemas de acionamentos elétricos. Executa a instalação e manutenção de iluminação e sinalização de segurança. - Eixo Tecnológico: Controle e Processos Industriais - Mercado de trabalho: Concessionárias do setor de energia elétrica; indústrias.' },
  //{ slug: 'especializacao-em-gestao-de-projetos-ead', nome: 'Especialização em Gestão de Projetos', modalidade: 'Especialização técnica', periodo: 'EAD', imagem: 'Especialização em Gestão de Projetos', valor: 'Especialização em Gestão de Projetos- EAD', descricao: '' },
  //{ slug: 'guia-de-turismo-ead', nome: 'Guia de Turismo', modalidade: 'Técnico', periodo: 'EAD', imagem: 'Técnico em Guia de Turismo', valor: 'Guia de Turismo-EAD', descricao: '' },
  //{ slug: 'comercio-ead', nome: 'Comércio', modalidade: 'Técnico', periodo: 'EAD', imagem: 'Técnico em Comércio', valor: 'Comércio-EAD', descricao: '' },
  //{ slug: 'secretariado-ead', nome: 'Secretariado', modalidade: 'Técnico', periodo: 'EAD', imagem: 'Técnico em Secretariado', valor: 'Secretariado-EAD', descricao: '' },
  //{ slug: 'transacoes-imobiliarias-ead', nome: 'Transações Imobiliárias', modalidade: 'Técnico', periodo: 'EAD', imagem: 'Técnico em Transações Imobiliárias', valor: 'Transações Imobiliárias-EAD', descricao: '' }
];

// URL da imagem do curso, ou null se o arquivo ainda não foi carregado.
// Consulta o disco a cada chamada: imagens novas aparecem sem reiniciar o servidor.
function urlImagem(curso) {
  const ext = EXTENSOES.find((e) => fs.existsSync(path.join(PASTA_IMAGENS, curso.imagem + e)));
  return ext ? '/img/cursos/' + encodeURIComponent(curso.imagem + ext) : null;
}

function comImagem(curso) {
  return Object.assign({}, curso, { imagemUrl: urlImagem(curso) });
}

// Destaques da descrição: cada rótulo abre um novo parágrafo, com o rótulo em negrito.
const ROTULOS = { 'eixo tecnológico': 'Eixo Tecnológico', 'atuação': 'Atuação', 'mercado de trabalho': 'Mercado de Trabalho' };
const RE_ROTULO = /\s*(?:-\s*)?(Eixo Tecnológico|Atuação|Mercado de Trabalho)\s*:\s*/i;

// Converte o texto da descrição em parágrafos [{ rotulo|null, texto }].
// Linhas em branco também separam parágrafos. Rótulos reconhecidos sem diferenciar maiúsculas.
function paragrafos(descricao) {
  const saida = [];
  (descricao || '').split(/\n\s*\n/).forEach((bloco) => {
    const partes = bloco.split(RE_ROTULO); // [texto, rótulo, texto, rótulo, texto, ...]
    const intro = partes[0].trim();
    if (intro) saida.push({ rotulo: null, texto: intro });
    for (let i = 1; i < partes.length; i += 2) {
      saida.push({ rotulo: ROTULOS[partes[i].toLowerCase()], texto: (partes[i + 1] || '').trim() });
    }
  });
  return saida;
}

module.exports = {
  paragrafos,
  CURSOS,
  VALORES: CURSOS.map((c) => c.valor),
  listar: () => CURSOS.map(comImagem),
  buscar: (slug) => {
    const i = CURSOS.findIndex((c) => c.slug === slug);
    if (i < 0) return null;
    return { curso: comImagem(CURSOS[i]), anterior: CURSOS[i - 1] || null, proximo: CURSOS[i + 1] || null };
  }
};
